{% set name = "preshed" %}
{% set version = "3.0.5" %}
{% set sha256sum = "c6d3dba39ed5059aaf99767017b9568c75b2d0780c3481e204b1daecde00360e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - msinttypes  # [win and vc<14]

  run:
    - python
    - cymem >=2.0.2,<2.1.0
    - murmurhash <1.1.0,>=0.28.0


test:
  imports:
    - preshed
    - preshed.counter
    - preshed.maps
    - preshed.tests
  requires:
    - pytest

about:
  home: https://github.com/explosion/preshed
  license: MIT
  license_file: LICENSE
  summary: Cython Hash Table for Pre-Hashed Keys
  description: |
    Simple but high performance Cython hash table mapping pre-randomized keys
    to void* values.
  doc_url: https://pypi.python.org/pypi/preshed
  doc_source_url: https://github.com/explosion/preshed/blob/master/README.rst
  dev_url: https://github.com/spacy-io/preshed

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
