{% set name = "preshed" %}
{% set version = "3.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c74c70078809bfddda17be96483c41d06d717934b07cab7921011d81758b357

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython >=0.28
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0

test:
  requires:
    - pip
    - pytest
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/preshed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cython Hash Table for Pre-Hashed Keys
  description: |
    Simple but high performance Cython hash table mapping pre-randomized keys
    to void* values.
  doc_url: https://pypi.python.org/pypi/preshed
  dev_url: https://github.com/spacy-io/preshed

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - ines
    - honnibal
    - adrianeboyd
