{% set name = "preshed" %}
{% set version = "1.0.0" %}
{% set sha256sum = "a6b3a9e34634600e3e410ec25e0debed4b65a47eb37514a063d189d1c425b4dd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256sum }}
  - url: https://raw.githubusercontent.com/explosion/preshed/master/bin/cythonize.py
    folder: bin

build:
  number: 0
  script:
   - rm PKG-INFO  # [unix]
   - del /q PKG-INFO  # [win]
   - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - msinttypes  # [win and vc<14]
    - python
    - setuptools
    - cymem >=1.30,<1.32
    - cython

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - cymem >=1.30,<1.32

test:
  imports:
    - preshed
    - preshed.counter
    - preshed.maps
    - preshed.tests
  requires:
    - pytest

about:
  home: https://github.com/explosion/preshed
  license: MIT
  license_file: LICENSE
  summary: Cython Hash Table for Pre-Hashed Keys
  description: |
    Simple but high performance Cython hash table mapping pre-randomized keys
    to void* values.
  doc_url: https://pypi.python.org/pypi/preshed
  doc_source_url: https://github.com/explosion/preshed/blob/master/README.rst
  dev_url: https://github.com/spacy-io/preshed

extra:
  recipe-maintainers:
    - rmax
