{% set name = "preshed" %}
{% set version = "3.0.6" %}
{% set sha256sum = "fb3b7588a3a0f2f2f1bf3fe403361b2b031212b73a37025aea1df7215af3772a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython >=0.28
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0
    - msinttypes  # [win and vc<14]
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0

test:
  requires:
    - pip
    - pytest
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/preshed
  license: MIT
  license_file: LICENSE
  summary: Cython Hash Table for Pre-Hashed Keys
  description: |
    Simple but high performance Cython hash table mapping pre-randomized keys
    to void* values.
  doc_url: https://pypi.python.org/pypi/preshed
  doc_source_url: https://github.com/explosion/preshed/blob/master/README.rst
  dev_url: https://github.com/spacy-io/preshed

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - ines
    - honnibal
    - adrianeboyd