travis:
  secure:
    BINSTAR_TOKEN: EsELzfStZYRdEPUmslykgjpJOa6v95OJATliklhRWD+xJgub3RfQKWpAM/NOyrs0EwRnmrygC2y7soVocs//U0azWVJmOfNhD1gX3NtO/6aai7ERvYwugh8GG667BS6YSYrF8/WUJ3mKSf4mFCGowpfUaSc7y8vFOjpYvf8jiMrzEae+N3AOo04mDVNW+cewxoK9py+gtvxMpT4CL/8XcEXmaCjakO2+Q82UJVpSq/CSQkQSA0NIyWI/tdkHS54wzWSuvJZnX9E96CpF7IqJKVGsz0yfiqYpqk2TkDDwmDjYbWma6iKy1/fj7jlR9oN2v+OpnXxD9Dx0xIif3+MjcAUlVBsJSXPcvVKE5f+/VBEIQ+Ex1j82lAHFmJp1NCCe5UmcxKRndGSyrwQTSSbnpB49DZF2Kk8pEVVViwu21bl4njSGa2DGv9ng21A60lV5xbQVy5xYAR/inxOi7r0Zi0JgmvXUwx7bMwHKMQ3Vj8gn5wkEB5CvG5BEnuYdwBBd5mDn2PrQLkx9Lw4W9v5WEgWr7mdgEZUl68DgouwiwRj52+yYx6SHYFXCHYvn4hTvpKpbFvPtqPUHQYuLi5OmwsK+1TgWLNfDaOqhgDOhoX9F56qtlSvkD0fElK8sxy+v9H8u94/VYjsHi/LsO2FtFZ93PZG1/SixevtUmWqF4q8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
