travis:
  secure:
    BINSTAR_TOKEN: DdB8UyjJqRI82hJ5oj6zOoXAiAyMO2MUlfx2NYUDJKhoG2B7ET9ovgDnmFuDpMNRczVrTjYc1gn4KcU3YYtTqiKEoO53v9/a3k45Mjc2YQ+7FhsWkKgeuo7XUWOvRXwUeSaZVJMAlp0/tiBdt0IJoPfGLpx1OHyNJWWWrvit0MbRq5ubl31Hislr+f3TkPLjuHDsuJTcozvxKmlvnG7HlSEIj6peeW3D3Tg5shGjA07pJK9nURa1UWFlJcYiAWiwcGdOLoYQ0NTOtu8rS0gw65tX1t+ysG1nq8GH4Yrz9hVZikaLidSFo8zsd8WT8LSpJR65u7kG9HQXuzEGqOvoSgeTY8wuLTx/2r+e4mmjW6uaCyw5ZLSISYa7k8gia3OXppvfsv18KjktJgcNl4YPMm0CeoIvl/645iILfexU1NjcigJaS6QbGRbTsPpPUKqbmOsimboOJKjtsnhzG+B5aHiH+sPWxjer+cGOhXZTkpKSzJmeCMsURplNCMYVIHyMtraIx95dAYzDhEs/9Giv5fQZTslZfCzKJO5ELaVM2c3OHucAedUoSN3VX90CZbvsRosSA4yzgsSqMjHGQJNcMf5Rb5jSD07X4Qq2ZZHmAtqpR8tmgAVwYEzl82JCGwJfRHWEDRWfmFFtZBR/Omxn9cRezFtotSw2XXPpwVuaQv4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
