travis:
  secure:
    BINSTAR_TOKEN: RcT8GjBBeUwGgkL9qVkr/cLu4xSYNtFBEIAp4uVo1ADKYsmdyIxjXRb3WYgwzfXj0d8bWgamIoAMxcgC1JZZ5yGu3R3edBYxMm9EvE1gmORt43dk1nPlJZURwVQjv+4B8NAtKe2gXuGNIkFm5QkPZtyTonIAP2SgDr4L7zaqnM/ozeKTc2BtdhWEghVnL3UenDSvh9nngbctzJ4nssJEI8vyup/yThICIlUUa6cbGJVGNYBvxLoMh5ffBgJ6bIut/TN35c9w+kSj6kgWDvQPFKXRgW/jT4xUcJnS6boaQxbpC66dbcZjvcg7xxw5yMMZqf/X0JlSpvHvMgkUsyrT+eqxBlcUtoHWBnHRgfSat+Nrice7sY4lYQ3ib1jYRH8MBuK7VRroCKs7QLEgkYgo1vC7Kd6H8NP+rDaTxrz0hfthfyXgbNvcojcYwWib03F+OBP5rZjgSNWlnQNnMIt0cB/UMdwPZUdSvmZkjYyi8q0XTwks9tLqYiSPOCfGi8A4uBt1DIJP/+cmRvysb64T1o7G5AFj43OZfjHX7Iwl7pMxiC5gpmMZ6m5XswIEF4e3LeJVCOGFLmhRE3DE4jD1g0terUrslQqYX+HCeGppHXgFsEeJaNjP7iL+sF+3n3dE3RSIxA4Cpk5iHevxkhtBM5FcS7RmJnBK7V4V7DO14ZA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
